// Package claude turns an effective doctrine into Claude Code configuration.
//
// Claude Code loads .claude/rules/ automatically, so the project's CLAUDE.md
// is never touched.
package claude

import (
	"fmt"
	"path/filepath"

	"github.com/disrupt-ed/doctrine-cli/internal/compose"
)

var (
	rulesDir = filepath.Join(".claude", "rules", "doctrine")
	skillDir = filepath.Join(".claude", "skills", "dependency-review")
)

// Owned are the directories this adapter owns. Their contents are replaced
// on every generate.
var Owned = []string{rulesDir, skillDir}

// Files returns the generated files, keyed by path relative to the project root.
func Files(e compose.Effective) map[string][]byte {
	files := map[string][]byte{}
	for _, d := range e.Doctrines {
		path := filepath.Join(rulesDir, d.Topic()+".md")
		files[path] = []byte(header(d.Name) + d.Body)
	}
	if e.HasOverrides() {
		files[filepath.Join(rulesDir, "project.md")] = []byte(header(".doctrine/") + e.ProjectMarkdown())
	}
	files[filepath.Join(skillDir, "SKILL.md")] = []byte(skill)
	return files
}

func header(source string) string {
	return fmt.Sprintf("<!-- Generated by doctrine from %s. Do not edit: change .doctrine/ and run `doctrine generate`. -->\n\n", source)
}

const skill = `---
name: dependency-review
description: Review a gem or Go module before adding it to this project. Use whenever you are about to add, replace or recommend a dependency, or when the developer asks about one.
argument-hint: NAME
---

<!-- Generated by doctrine. Do not edit: change .doctrine/ and run ` + "`doctrine generate`" + `. -->

# Dependency Review

Review ` + "`$ARGUMENTS`" + ` before it is added. Follow the dependency doctrine in ` + "`.claude/rules/doctrine/`" + `.

1. State the actual need in one sentence.
2. Check whether the language, the framework or an existing dependency already covers it. Search the codebase.
3. Gather facts. If the ` + "`doctrine`" + ` CLI is installed, run:

   ` + "```bash" + `
   doctrine dependency inspect NAME
   ` + "```" + `

   Otherwise check the registry (rubygems.org or pkg.go.dev) and the source repository yourself: last release, last commit, open issues, supported versions, transitive dependencies.

4. Report the facts first, then your recommendation in one or two sentences, with the main alternative.
5. If the developer still wants the dependency, add it.
`
