package claude

import (
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/disrupt-ed/doctrine-cli/doctrines"
	"github.com/disrupt-ed/doctrine-cli/internal/compose"
	"github.com/disrupt-ed/doctrine-cli/internal/manifest"
)

// The hand-crafted output used in the evaluation is the golden file set:
// generation must reproduce it exactly.
func TestGoldenEvalOutput(t *testing.T) {
	for app, extends := range map[string][]string{"campfire": {"rails/default"}, "miniflux": {"go/default"}} {
		t.Run(app, func(t *testing.T) {
			golden := filepath.Join("..", "..", "..", "eval", "claude-output", app)
			m := manifest.Manifest{Version: 1, Doctrines: manifest.Release(doctrines.Release), Extends: extends}
			e, err := compose.Compose(doctrines.FS, m, t.TempDir())
			if err != nil {
				t.Fatal(err)
			}
			got := Files(e)
			want := map[string]string{}
			filepath.WalkDir(golden, func(path string, d fs.DirEntry, err error) error {
				if err != nil || d.IsDir() {
					return err
				}
				rel, _ := filepath.Rel(golden, path)
				if strings.HasPrefix(rel, ".doctrine") {
					return nil
				}
				data, _ := os.ReadFile(path)
				want[rel] = string(data)
				return nil
			})
			if len(want) == 0 {
				t.Fatal("no golden files")
			}
			if len(got) != len(want) {
				t.Errorf("got %d files, want %d", len(got), len(want))
			}
			for path, content := range want {
				if string(got[path]) != content {
					t.Errorf("%s differs from golden file", path)
				}
			}
			if string(m.Marshal()) != readFile(t, filepath.Join(golden, manifest.Path)) {
				t.Error("manifest differs from golden file")
			}
		})
	}
}

func TestProjectOverridesFile(t *testing.T) {
	m := manifest.Manifest{Version: 1, Doctrines: "0.1", Extends: []string{"go/default"}, Engineering: map[string]string{"yagni": "normal"}}
	e, err := compose.Compose(doctrines.FS, m, t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	project := string(Files(e)[filepath.Join(rulesDir, "project.md")])
	if !strings.HasPrefix(project, "<!-- Generated by doctrine from .doctrine/.") || !strings.Contains(project, "Build for today: normal") {
		t.Fatalf("project.md:\n%s", project)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
